# Generated by Django 5.0.7 on 2024-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('emergency_phone_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
