# Generated by Django 5.0.7 on 2024-07-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_doctor_remove_user_id_remove_user_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='causes_of_disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
    ]
