# Generated by Django 5.0.7 on 2024-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_remove_appointment_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='allergy',
            field=models.JSONField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='causes_of_disease',
            field=models.JSONField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.JSONField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.JSONField(default=None, max_length=100),
        ),
    ]
