# Generated by Django 5.0.7 on 2024-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_appointment_allergy_appointment_causes_of_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='allergy',
            field=models.JSONField(default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='causes_of_disease',
            field=models.JSONField(default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='disease',
            field=models.JSONField(default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.JSONField(default=list, max_length=100),
        ),
    ]
